### ISSUE TITLE
[FlightSQL][Go] Support for metadata requests

### ISSUE THREAD

**Issue by stoffeastrom** [apache/arrow#12496]
Hi 👋 

Are there any plans to support metadata requests with the `golang` `flight` client❓

**Comment by zeroshade** [comment]
Which metadata requests aren't currently supported? for record batch handling, both the reader and writer support handling the `AppMetadata` field of the message. Which request do you need that isn't yet supported?

**Comment by stoffeastrom** [comment]
I was trying to find these

```yaml
CommandGetCatalogs: list catalogs in a database.
CommandGetCrossReference: list foreign key columns that reference a particular other table.
CommandGetDbSchemas: list schemas in a catalog.
CommandGetExportedKeys: list foreign keys referencing a table.
CommandGetImportedKeys: list foreign keys of a table.
CommandGetPrimaryKeys: list primary keys of a table.
CommandGetSqlInfo: get information about the database itself and its supported SQL dialect.
CommandGetTables: list tables in a catalog/schema.
CommandGetTableTypes: list table types supported (e.g. table, view, system table).
```

after read the blog [post](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/) 
but couldn't find anything under `go` path in the repo. I'll look into the `AppMetadata`. 

Thanks for your reply @zeroshade
