### ISSUE TITLE
Create wheels for M1 Silicon for older versions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29228]
The Snowflake data warehouse has a python client that requires an older version of pyarrow-->=3.0.0,<3.1.0:

<https://docs.snowflake.com/en/user-guide/python-connector-pandas.html#requirements>

I've tried everything I can think of or read about to get the older versions of pyarrow working on my M1 but to no avail.  Snowflake is saying they won't update their connector until September:

 

<https://github.com/snowflakedb/snowflake-connector-python/issues/815> 

**Reporter**: [Michelangelo D'Agostino](https://issues.apache.org/jira/browse/ARROW-13583)

<sub>**Note**: *This issue was originally created as [ARROW-13583](https://issues.apache.org/jira/browse/ARROW-13583). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by eitsupi** [comment]
I am wondering if this issue can be closed since it seems out of date and snowflake-connector-python already seems to be following a newer version of pyarrow.

```toml
[build-system]
requires = [
    # The minimum setuptools version is specific to the PEP 517 backend,
    # and may be stricter than the version required in `setup.py`
    "setuptools>=40.6.0",
    "wheel",
    "cython",
    # Must be kept in sync with the `setup_requirements` in `setup.cfg`
    "pyarrow>=10.0.1,<10.1.0",
]
```

https://github.com/snowflakedb/snowflake-connector-python/blob/e937591356c067a77f34a0a42328907fda792c23/pyproject.toml#L9
