### ISSUE TITLE
[Python] ImportError: DLL load failed while importing lib

### ISSUE THREAD

**Issue by luifrancgom** [apache/arrow#40320]
### Describe the bug, including details regarding any error messages, version, and platform.

# Describe the bug

I am using the package `sktime` that uses `pyarrow` and I am getting the following error:

```bash
ImportError: DLL load failed while importing lib: The specified procedure could not be found.
```
## Traceback

```python
import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Usuario\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: DLL load failed while importing lib: The specified procedure could not be found.
```

</details>

# Version

`pyarrow 13.0.0` installed using `pypi` channel

# Platform

I am using the following OS:

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎06-‎26
OS build	22621.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0
```
With `python 3.11.8` and `conda 24.1.2`

### Component(s)

Python

**Comment by amoeba** [comment]
Hi @luifrancgom, thanks for the report. Can you provide a set of steps that reproduce the error, preferably using a fresh virtualenv or conda environment? I tried just now and am not having any trouble importing pyarrow 13.0.0.

**Comment by luifrancgom** [comment]
You are right. I try the following configuration in yaml file called `environment.yml`:

```yml
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env list
#    conda activate test_pyarrow
#    conda env remove --name test_pyarrow

name: test_pyarrow
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pip
  - pip:
      - pyarrow==13.0.0
      - sktime==0.27.0
```
And when running this script

```py
import sktime
import pyarrow
```
It works. I am going to close the issue and find the problem because it is not related to `pyarrow` or `sktime`
